### PR TITLE
updated scope list and removed hydra.consent.*

### PR DESCRIPTION
**Pull request by abusaidm**

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you!

**Comment by aeneasr** [comment]
This will be released as 0.10.0-alpha.9 - could you update the consent app version in the tutorial as well?

**Comment by abusaidm** [comment]
by the way, before i update the docs. I noticed that in the docs you are using multiple versions of hydra is that intentional?

**Comment by aeneasr** [comment]
No, docs should always be the latest version. Unfortunately, GitBook and Apiary do not support versioned docs as of now.

**Pull request merged**
